from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_spec = importlib.util.spec_from_file_location(
    "check_conventions", Path(__file__).resolve().parents[1] / "scripts" / "check_conventions.py"
)
check_conventions = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(check_conventions)


def _scan_one(tmp_path: Path, text: str):
    target = tmp_path / "sample.md"
    target.write_text(text, encoding="utf-8")
    return check_conventions.scan([target])


@pytest.mark.parametrize(
    ("text", "because"),
    [
        ("a sentence — interrupted", "em dash"),
        ("a range 1 – 2", "en dash"),
        ("ship it \U0001F680", "emoji"),
        ("Co-Authored-By: someone", "co-author trailer"),
        ("Generated with Claude Code", "attribution footer"),
        ("written by codex", "attribution prose"),
        ("GROQ_API_KEY=gsk_abcdefghijklmnopqrstuvwxyz012345", "live credential"),
    ],
)
def test_the_blocking_rules_actually_block(tmp_path, text, because):
    failures, _ = _scan_one(tmp_path, text)
    assert failures, f"{because} was not caught"


@pytest.mark.parametrize(
    "text",
    [
        "If a number cannot be regenerated by a script, it does not go in the README.",
        "Set GROQ_API_KEY in the Render dashboard, never in the repo.",
        "The dash-free sentence, with a comma instead.",
        "See llm/providers/quotas.yaml for the per-provider limits.",
    ],
)
def test_the_blocking_rules_do_not_fire_on_correct_prose(tmp_path, text):
    """The false positives that matter, each one a real line from these repos.

    `regenerated by a script` is the phrase QUALITY.md uses to demand
    reproducibility, and the first version of this checker failed on it. A checker
    that cries wolf is a checker somebody adds a skip flag to.
    """
    failures, _ = _scan_one(tmp_path, text)
    assert failures == []


def test_absolutes_warn_rather_than_block(tmp_path):
    """Rule 5 is a judgement call, so it prints and a reviewer looks.

    `CI blocks regressions` is a mechanical description and correct. `the gateway
    blocks prompt injection` is the claim the rule exists to stop. No regex can tell
    those apart, so the script refuses to pretend it can.
    """
    failures, warnings = _scan_one(tmp_path, "the gateway blocks prompt injection")
    assert failures == []
    assert warnings
