#!/usr/bin/env python
"""Convention checks a human would otherwise have to do by eye.

Every rule here was previously enforced by trust: written in CONTRIBUTING.md, and
verified only when someone happened to read the diff. That works for one person and
stops working the moment more than one author is committing, which is now the case.

Scans tracked files only, because untracked working files (SPEC, BACKLOG, LEARNING,
QUOTAS) are deliberately private and their conventions do not matter to a reader.

Two tiers. FAIL is unambiguous and blocks. WARN is a judgement call and prints, so a
reviewer looks rather than a script guesses.

Run: uv run python scripts/check_conventions.py
"""

from __future__ import annotations

import re
import subprocess
import sys
import unicodedata
from pathlib import Path

# Two files necessarily contain the strings this searches for: the checker, and the
# test that proves each rule fires. Scanning either teaches everyone to pass --skip.
# Nothing else is exempt, including other tests, because a fixture is exactly where a
# real credential gets pasted "just for a minute".
EXEMPT = {Path(__file__).name, "test_conventions.py"}

TEXT_SUFFIXES = {
    ".py", ".md", ".txt", ".yml", ".yaml", ".toml", ".json", ".ts", ".tsx",
    ".js", ".jsx", ".css", ".html", ".sh", ".cfg", ".ini", ".sql",
}

EN_DASH = "–"
EM_DASH = "—"

# A tool name is required after "generated by", because "regenerated by a script" is
# the phrase QUALITY.md uses to demand reproducibility and is the opposite of a tell.
# The checker caught that on its first run, against QUALITY.md itself.
ATTRIBUTION = re.compile(
    r"co-authored-by"
    r"|(?:generated|written|authored) (?:with|by) "
    r"(?:claude|codex|cursor|grok|copilot|chatgpt|an? ai)"
    r"|with the help of (?:claude|codex|cursor|grok|copilot|chatgpt)",
    re.IGNORECASE,
)

# Live credential shapes, not the names of environment variables. `GROQ_API_KEY` in
# a config file is correct and expected; `GROQ_API_KEY=gsk_...` is the incident.
SECRETS = re.compile(
    r"\b(?:sk-[A-Za-z0-9]{16,}|gsk_[A-Za-z0-9]{16,}|xai-[A-Za-z0-9]{16,}"
    r"|AIza[A-Za-z0-9_\-]{20,}|ghp_[A-Za-z0-9]{20,}|glpat-[A-Za-z0-9_\-]{16,})",
)

# Credibility rule 5 from the benchmarks brief. A judgement call, because "CI fails
# the check" is fine and "the gateway blocks injection" is not, and only a reader can
# tell which one a sentence is doing.
ABSOLUTES = re.compile(r"\b(?:solves|blocks|prevents)\b", re.IGNORECASE)


def tracked_text_files() -> list[Path]:
    # -z, because git quotes any path holding a non-ASCII or unusual byte and
    # prints it in escaped octal form instead. That quoted string names no file
    # on disk, so the path fails is_file() and drops out of the scan without
    # saying so. A file could then carry a credential past this checker by being
    # named in Devanagari, which is a corpus this portfolio actually has.
    out = subprocess.run(
        ["git", "ls-files", "-z"], capture_output=True, text=True, check=True
    ).stdout.split(chr(0))
    return [
        p
        for name in out
        if name
        and (p := Path(name)).suffix in TEXT_SUFFIXES
        and p.name not in EXEMPT
        and p.is_file()
    ]


def is_emoji(char: str) -> bool:
    if char in "‍️":
        return False
    return unicodedata.category(char) == "So" and ord(char) > 0x2100


def scan(paths: list[Path]) -> tuple[list[str], list[str]]:
    failures: list[str] = []
    warnings: list[str] = []

    for path in paths:
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (UnicodeDecodeError, OSError):
            continue

        for number, line in enumerate(lines, start=1):
            where = f"{path}:{number}"

            if EM_DASH in line or EN_DASH in line:
                failures.append(
                    f"{where}: em or en dash. Use a comma, a colon, or split the sentence."
                )

            if found := [c for c in line if is_emoji(c)]:
                failures.append(f"{where}: emoji {found!r}")

            if ATTRIBUTION.search(line):
                failures.append(f"{where}: AI attribution")

            if match := SECRETS.search(line):
                failures.append(f"{where}: looks like a live credential ({match.group()[:8]}...)")

            if match := ABSOLUTES.search(line):
                warnings.append(
                    f"{where}: '{match.group()}'. Prefer a measured claim, such as "
                    "'reduced X from A to B under threat model T'."
                )

    return failures, warnings


# Names that must appear in neither a tracked file nor a commit message. The local
# agent instruction files are kept out of git precisely so the repo does not advertise
# how it was built, and a commit message naming one defeats that permanently, because
# history cannot be quietly edited once it is pushed.
#
# Not theoretical: a seed commit in a sibling repo explained why those files are
# excluded, by name, which is the same tell somewhere much harder to remove.
TELLS = re.compile(
    r"\bclaude\b|\bcodex\b|\bcursor\b|\bgrok\b|\bcopilot\b|\bchatgpt\b|\bAGENTS\.md\b",
    re.IGNORECASE,
)


def commit_messages(count: int = 20) -> list[tuple[str, str]]:
    """Recent commit messages, as (short sha, body).

    Split on a record separator git will not emit on its own, rather than on a string
    a message could itself contain. A separator a commit can produce lets one message
    end the parse early and hide every message after it.
    """
    separator = chr(30)
    out = subprocess.run(
        ["git", "log", f"-{count}", f"--format=%h %B{separator}"],
        capture_output=True,
        text=True,
    )
    if out.returncode != 0:
        # Not an empty list. Returning one here would report "conventions clean"
        # for a repository whose commit messages were never read, which is the
        # failure mode a checker must never have.
        raise RuntimeError(
            "git log failed, so no commit message was scanned: "
            + out.stderr.strip()
        )

    messages = []
    for block in out.stdout.split(separator):
        block = block.strip()
        if block:
            sha, _, body = block.partition(" ")
            messages.append((sha, body))
    return messages


def scan_commits() -> list[str]:
    problems = []
    for sha, body in commit_messages():
        where = f"commit {sha}"
        if EM_DASH in body or EN_DASH in body:
            problems.append(f"{where}: em or en dash in the message")
        if ATTRIBUTION.search(body):
            problems.append(f"{where}: AI attribution in the message")
        if match := TELLS.search(body):
            problems.append(
                f"{where}: names {match.group()!r}, which this repo does not advertise"
            )
        if found := [c for c in body if is_emoji(c)]:
            problems.append(f"{where}: emoji {found!r} in the message")
    return problems


def main() -> int:
    paths = tracked_text_files()
    failures, warnings = scan(paths)
    failures.extend(scan_commits())

    if warnings:
        print(f"REVIEW ({len(warnings)}), not blocking:")
        for line in warnings:
            print(f"  {line}")
        print()

    if failures:
        print(f"FAIL ({len(failures)}):")
        for line in failures:
            print(f"  {line}")
        return 1

    print(f"conventions clean across {len(paths)} tracked files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
